[features]
seeds = false
skip-lint = false
[programs.localnet]
price_oracle = "2QQpxGtYLFqKZp5SSejPBMPfWUGq1K3GKN8gEtJUgf6q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/matthewchukwuemeka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
